Update image-update.md to allow secret creation
Patch the current documentation to allow continuation of line where required to create the docker-registry secret in the example.  Without this the example will not run due to a bash error.

Output of error this fixes:

```
secret/ecr-credentials created (dry run)
/bin/bash: line 5: -o: command not found
error: no objects passed to apply
```

Signed-off-by: Dan Stone <stone@moonfarmer.com>